<?php
/**
 * EngineTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RemapDB
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RemapDB REST API Documentation
 *
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.64
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RemapDB;

use PHPUnit\Framework\TestCase;

/**
 * EngineTest Class Doc Comment
 *
 * @category    Class
 * @description Engine object
 * @package     RemapDB
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EngineTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Engine"
     */
    public function testEngine()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "slug"
     */
    public function testPropertySlug()
    {
    }

    /**
     * Test attribute "engine_code"
     */
    public function testPropertyEngineCode()
    {
    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {
    }

    /**
     * Test attribute "capacity"
     */
    public function testPropertyCapacity()
    {
    }

    /**
     * Test attribute "cylinders"
     */
    public function testPropertyCylinders()
    {
    }

    /**
     * Test attribute "engine_type"
     */
    public function testPropertyEngineType()
    {
    }

    /**
     * Test attribute "fuel"
     */
    public function testPropertyFuel()
    {
    }

    /**
     * Test attribute "ecus"
     */
    public function testPropertyEcus()
    {
    }

    /**
     * Test attribute "tcus"
     */
    public function testPropertyTcus()
    {
    }

    /**
     * Test attribute "performance"
     */
    public function testPropertyPerformance()
    {
    }
}
